Fix Terraform installation directory creation

diff --git a/infra/Jenkinsfile b/infra/Jenkinsfile
--- a/infra/Jenkinsfile
+++ b/infra/Jenkinsfile
@@ -21,24 +21,36 @@ pipeline {
         }
 
         stage("Install Terraform") {
-    steps {
-        sh '''
-            set -x
+            steps {
+                sh '''
+                    set -x
+                    set -e
 
-            # Remove old terraform directory if exists
-            rm -rf infra/terraform-bin
+                    # Ensure we're in the workspace root
+                    cd ${WORKSPACE}
 
-            echo "Downloading Terraform..."
-            wget -q https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
+                    # Remove old terraform directory if exists
+                    rm -rf infra/terraform-bin
 
-            unzip -o terraform_1.9.8_linux_amd64.zip
+                    echo "Downloading Terraform..."
+                    wget -q https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
 
-            mkdir -p infra/terraform-bin
-            mv terraform infra/terraform-bin/terraform
-            chmod +x infra/terraform-bin/terraform
-        '''
-    }
-}
+                    echo "Extracting Terraform..."
+                    unzip -o terraform_1.9.8_linux_amd64.zip
+
+                    # Create directory and move terraform binary
+                    mkdir -p infra/terraform-bin
+                    mv terraform infra/terraform-bin/terraform
+                    chmod +x infra/terraform-bin/terraform
+
+                    # Clean up zip file
+                    rm -f terraform_1.9.8_linux_amd64.zip LICENSE.txt
+
+                    # Verify terraform is installed
+                    ${WORKSPACE}/infra/terraform-bin/terraform version
+                '''
+            }
+        }
 
         stage("Terraform Init") {
             steps {
